[screenshot]
folder = "C:/Users/omarz/Documents/paul/burst"
folder_burst= "C:/Users/omarz/Documents/paul/singleshot"
name = "screenshot.png"
number_of_screens = 5
interval_seconds = 2  # Time interval between screenshots in seconds
